name: fe_master
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #* --- firebase ---
  firebase_core: ^2.4.1
  firebase_app_check: ^0.1.1+8
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.2.1
  firebase_in_app_messaging: ^0.7.0+10
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2
  firebase_storage: ^11.0.10
  #*  --- firebase mock ---
  firebase_auth_mocks: ^0.9.2
  google_sign_in_mocks: ^0.2.1
  firebase_storage_mocks: ^0.6.0+1
  fake_cloud_firestore: ^2.1.0
  #*  --- state management ---
  states_rebuilder: ^6.2.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0
  #*  --- rest api ---
  http: ^0.13.4
  dio: ^4.0.4
  dio_log: ^2.0.3
  #*  --- images ---
  flutter_fadein: ^2.0.0
  transparent_image: ^2.0.0
  shimmer: ^2.0.0
  image_picker: ^0.8.4+11
  flutter_cache_manager: ^3.3.0
  #*  --- tools ---
  device_preview: ^1.0.0
  validators: ^3.0.0
  overlay_support: ^2.0.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  connectivity_plus: ^2.2.1
  keyboard_dismisser: ^3.0.0
  english_words: ^4.0.0
  uuid: ^3.0.6

  # pkg_master:
  #   path: ./packages/pkg_master
  # pkg_master:
  #   git:
  #     url: https://github.com/nostracode/pkg_master.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/json/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader-Regular.ttf
        - asset: assets/fonts/Newsreader-Italic.ttf
          style: italic
        - asset: assets/fonts/Newsreader-Bold.ttf
          weight: 700
