name: fe_master
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #
  firebase_core: ^1.13.1
  #
  firebase_app_check: ^0.0.6+7
  firebase_analytics: ^9.1.2
  #
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.9
  firebase_auth: ^3.3.8
  firebase_auth_web: ^3.3.8
  google_sign_in: ^5.2.4
  google_sign_in_web: ^0.10.0+5
  firebase_storage: ^10.2.8
  firebase_storage_web: ^3.2.9
  # mock
  firebase_auth_mocks: ^0.8.2
  google_sign_in_mocks: ^0.2.1
  firebase_storage_mocks: ^0.5.0
  fake_cloud_firestore: ^1.2.1
  #
  states_rebuilder: ^6.0.0
  google_fonts: ^2.3.1
  # get: ^4.6.1
  fluttertoast: ^8.0.9
  logger: ^1.1.0
  connectivity_plus: ^2.2.1
  keyboard_dismisser: ^2.0.1
  english_words: ^4.0.0
  flutter_fadein: ^2.0.0
  transparent_image: ^2.0.0
  shimmer: ^2.0.0
  image_picker: ^0.8.4+11
  flutter_cache_manager: ^3.3.0
  url_strategy: ^0.2.0
  validators: ^3.0.0
  dio: ^4.0.4
  flutter_alice: ^1.0.2
  overlay_support: ^1.2.1

  # pkg_master:
  #   path: ./packages/pkg_master
  # pkg_widget_collection:
  #   path: ./packages/pkg_widget_collection
  #
  # pkg_master:
  #   git:
  #     url: https://github.com/nostracode/pkg_master.git
  # pkg_widget_collection:
  #   git:
  #     url: https://github.com/nostracode/pkg_widget_collection.git
  #
  #
  # * import package from git repo
  # <package-name>:
  #   git:
  #     url: <git-url>
  #   ref: <branch-on-git>
  #   path: <path/to/pkg_master>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/json/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader-Regular.ttf
        - asset: assets/fonts/Newsreader-Italic.ttf
          style: italic
        - asset: assets/fonts/Newsreader-Bold.ttf
          weight: 700
