// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDR5alackcAV3y3an61GdqeSO-X7tBAiA',
    appId: '1:835126305601:web:5e6641a6e73ca4e5fa77c0',
    messagingSenderId: '835126305601',
    projectId: 'fe-master',
    authDomain: 'fe-master.firebaseapp.com',
    databaseURL: 'https://fe-master-default-rtdb.firebaseio.com',
    storageBucket: 'fe-master.appspot.com',
    measurementId: 'G-5YRVJPSW9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9R03fdA1EyEHvWB3m2QYIIwKrxI8qhU',
    appId: '1:835126305601:android:7a0a89f9090e8008fa77c0',
    messagingSenderId: '835126305601',
    projectId: 'fe-master',
    databaseURL: 'https://fe-master-default-rtdb.firebaseio.com',
    storageBucket: 'fe-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jOvqiYM9TAPcA7tSjX7GVFZw6uvxrm4',
    appId: '1:835126305601:ios:3618168b8bdf3ef6fa77c0',
    messagingSenderId: '835126305601',
    projectId: 'fe-master',
    databaseURL: 'https://fe-master-default-rtdb.firebaseio.com',
    storageBucket: 'fe-master.appspot.com',
    androidClientId: '835126305601-62j33lo2p2ts8egj775t0hl02168itur.apps.googleusercontent.com',
    iosClientId: '835126305601-b86ib5k6jtrm6lsg8u13vvf2qdoqr5rq.apps.googleusercontent.com',
    iosBundleId: 'com.nostracode.fe-master',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jOvqiYM9TAPcA7tSjX7GVFZw6uvxrm4',
    appId: '1:835126305601:ios:3618168b8bdf3ef6fa77c0',
    messagingSenderId: '835126305601',
    projectId: 'fe-master',
    databaseURL: 'https://fe-master-default-rtdb.firebaseio.com',
    storageBucket: 'fe-master.appspot.com',
    androidClientId: '835126305601-62j33lo2p2ts8egj775t0hl02168itur.apps.googleusercontent.com',
    iosClientId: '835126305601-b86ib5k6jtrm6lsg8u13vvf2qdoqr5rq.apps.googleusercontent.com',
    iosBundleId: 'com.nostracode.fe-master',
  );
}
